#!/usr/bin/env bash
# This script that displays Best School 10 times, but for the 9th iteration,
# displays Best School and then Hi on a new line

counter=1
while [ $counter -le 20 ]
do
    echo $counter
    if [ $counter -eq 4 ]
    then
	echo "bad luck from China"
    elif [ $counter -eq 9 ]
    then
	echo "bad luck from Japan"
    elif [ $counter -eq 17 ]
    then
	echo "bad luck from Italy"
    fi
    ((counter++))
done
